### PR TITLE
update course number

### PR DESCRIPTION
**Pull request by ADSWT518**
**请确认以下事项**

- [x] 提交的项目均是自己的原创工作。如果您正在帮助其他人添加项目，请确认已经取得项目所有者的许可。
- [x] 项目链接可访问。如果这是一个 GitHub 项目，它有 README(.md) 文件，并且不含受版权保护的材料。
- [x] 项目相关课程的作业提交已截止。

Since all course numbers in the Computer Science Department were updated since the class of 2020, I think it is necessary to update the new course numbers for this project. At the same time, the original course numbers have been retained. (I made the changes manually based on the data on [plus.sjtu.edu.cn](https://plus.sjtu.edu.cn/course-plus/), so there may still be errors despite my multiple checks.)

The style-checking script has also been updated.

### CODE REVIEW

**Comment by ADSWT518** [comment]
Oh, it seems that some existing links are no longer accessible, such as [PsyduckLiu/CS241--Problem_solving_and_practice](https://github.com/PsyduckLiu/CS241--Problem_solving_and_practice). :cold_sweat:

**Comment by ADSWT518** [comment]
Removed :smiley:

**Comment by skyzh** [comment]
Thanks a lot!

**Comment by ADSWT518** [comment]
Thank you! And thank you for inviting me to the orgnization! :laughing:

**Pull request merged**
