### PR TITLE
course: add CS356 project and sort project content

### PR DESCRIPTION
**Pull request by Victrid**
Added my project for CS356: Project Workshop of Operating System
Because projects of this course may have a certain pattern, it seems that they are selected from three projects in turn, so the small items of Project 2 are adjusted to facilitate the query.

**请确认以下事项**

- [x] 提交的项目均是自己的原创工作。如果您正在帮助其他人添加项目，请确认已经取得项目所有者的许可。
- [x] 项目链接可访问。如果这是一个 GitHub 项目，它有 README(.md) 文件，并且不含受版权保护的材料。
- [x] 项目相关课程的作业提交已截止。

### CODE REVIEW

**Comment by Victrid** [comment]
It seems that some of the URLs not from mine is invalid now.

**Review by skyzh — APPROVED** [review]
Looks good! For the invalid URLs, would you please remove them in this PR?

**Comment by skyzh** [comment]
Checking all URLs might lead to rate limit of GitHub APIs. Therefore, I am still in favor of simply checking diff URLs.

**Comment by skyzh** [comment]
https://github.com/david990917/My-Computer-Science-Learning/tree/master/CPP-Programming-Course -> https://github.com/david990917/CPP-PROGRAMMING

**Comment by Victrid** [comment]
OK, then I'll reset the updated scripts

**Review by skyzh — APPROVED** [review]
In fact, I pretty like the new lint display style. We could do it in another PR.

**Pull request merged**
