### PR TITLE
course: add CS356 by KoalaYan

### PR DESCRIPTION
**Pull request by KoalaYan**
**请确认以下事项**

- [x] 提交的项目均是自己的原创工作。如果您正在帮助其他人添加项目，请确认已经取得项目所有者的许可。
- [x] 项目链接可访问。如果这是一个 GitHub 项目，它有 README(.md) 文件，并且不含受版权保护的材料。
- [x] 项目相关课程的作业提交已截止。

### CODE REVIEW

**Comment by KoalaYan** [comment]
So what's wrong if the greeting program printing "#Error: Resource not accessible by integration"?

**Comment by skyzh** [comment]
Sorry for disruption! It seems that GitHub's official workflow is not working. I'll remove that.

**Comment by Galaxies99** [comment]
Required checks passed. Maybe something wrong with the greeting scripts? @skyzh

**Comment by Galaxies99** [comment]
Required test passed. It seems there are something wrong with the greeting script.

**Comment by skyzh** [comment]
removed in #40

**Pull request merged**
